const API='https://acervo-leoalfa.onrender.com',KEY='leodition_central_token',ORIGINS={acervo:'https://acervo-leoalfa.onrender.com',repografia:'https://repografia.leodition.com.br'};
const $=id=>document.getElementById(id),message=text=>{$('status').textContent=text;};let requestSequence=0;
async function api(path,{token=localStorage.getItem(KEY),...options}={}){const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),'X-Acervo-Activity':'1',...options.headers},signal:AbortSignal.timeout(20000),cache:'no-store'}),data=await r.json();if(!r.ok){const e=Error(data.erro||'Não foi possível concluir.');e.status=r.status;throw e;}return data;}
const params=new URLSearchParams(location.search);const pending={destino:params.get('destino'),desafio:params.get('desafio'),estado:params.get('estado')};
function showLogin(){requestSequence++;$('account').hidden=true;$('loginForm').hidden=false;$('services').replaceChildren();$('accountName').textContent='';$('accountDetails').textContent='';$('password').value='';$('username').value='';}
async function signOut(){const token=localStorage.getItem(KEY);localStorage.removeItem(KEY);showLogin();message('Selecione outra conta para entrar.');$('password').type='password';$('showPassword').textContent='Mostrar';$('showPassword').setAttribute('aria-label','Mostrar senha');try{if(token)await api('/api/auth/logout',{token,method:'POST',body:'{}'});}catch{}$('username').focus();}
async function requiredPassword(user){if(!user.senha_redefinir||user.acesso_mestre)return;await new Promise(resolve=>{const d=document.createElement('dialog');d.innerHTML='<form method="post"><h2>Defina sua nova senha</h2><p>Escolha uma senha pessoal para continuar.</p><label>Nova senha<input name="nova" type="password" required minlength="6" maxlength="128" autocomplete="new-password"></label><label>Confirme a senha<input name="confirmacao" type="password" required minlength="6" maxlength="128" autocomplete="new-password"></label><p data-error role="alert"></p><button type="submit" class="primary">Salvar nova senha</button><button type="button" class="secondary" data-exit>Sair</button></form>';document.body.append(d);d.addEventListener('cancel',e=>e.preventDefault());d.querySelector('[data-exit]').onclick=()=>{d.close();d.remove();signOut();resolve(false);};d.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('[type=submit]'),error=f.querySelector('[data-error]');if(f.nova.value!==f.confirmacao.value){error.textContent='As senhas precisam ser iguais.';return;}b.disabled=true;try{await api('/api/auth/minha-senha',{method:'PUT',body:JSON.stringify({nova_senha:f.nova.value})});user.senha_redefinir=false;d.close();d.remove();resolve(true);}catch(e){error.textContent=e.message;}finally{b.disabled=false;}};d.showModal();});}
async function grant(destino){message('Abrindo seu sistema…');const data=await api('/api/auth/central/codigo',{method:'POST',body:JSON.stringify({destino,desafio:pending.desafio,estado:pending.estado})});const url=new URL(data.url);if(url.origin!==ORIGINS[destino]||url.pathname!=='/central/entrada.html')throw Error('Endereço de entrada inválido.');location.replace(url.href);}
async function enter(user){const sequence=++requestSequence;await requiredPassword(user);if(!localStorage.getItem(KEY)||sequence!==requestSequence)return;const data=await api('/api/auth/central/destinos');if(sequence!==requestSequence)return;$('loginForm').hidden=true;$('account').hidden=false;$('accountName').textContent=data.usuario.nome||data.usuario.usuario;$('accountDetails').textContent='@'+data.usuario.usuario+(data.usuario.acesso_mestre?' · Acesso administrativo':'')+[data.usuario.email,data.usuario.telefone].filter(Boolean).map(x=>' · '+x).join('');$('services').replaceChildren();for(const service of data.destinos){const b=document.createElement('button'),title=document.createElement('strong'),description=document.createElement('span');b.type='button';title.textContent=service.nome+' →';description.textContent=service.descricao;b.append(title,description);b.onclick=async()=>{b.disabled=true;try{if(service.id===pending.destino&&pending.desafio&&pending.estado)await grant(service.id);else location.assign(service.origem+'/central/entrada.html?destino='+service.id);}catch(e){message(e.message);}finally{b.disabled=false;}};$('services').append(b);}message('Escolha o sistema que deseja abrir.');if(pending.destino&&pending.desafio&&pending.estado){if(data.destinos.some(s=>s.id===pending.destino))await grant(pending.destino);else message('Esta conta não tem acesso ao sistema solicitado. Escolha uma opção permitida ou troque de conta.');}}
async function restore(){const token=localStorage.getItem(KEY);if(!token)return;message('Conferindo seu acesso…');try{await enter(await api('/api/auth/me'));}catch(e){if(e.status===401){localStorage.removeItem(KEY);showLogin();}message(e.message);$('retry').hidden=false;}}
$('loginForm').onsubmit=async e=>{e.preventDefault();const b=$('submitLogin');b.disabled=true;message('Conferindo usuário e senha…');try{const data=await api('/api/auth/login',{token:null,method:'POST',body:JSON.stringify({usuario:$('username').value,senha:$('password').value})});localStorage.setItem(KEY,data.token);$('password').value='';await enter(data);}catch(e){message(e.name==='TimeoutError'?'O servidor demorou para responder. Tente novamente.':e.message);}finally{b.disabled=false;}};$('switchAccount').onclick=signOut;$('retry').onclick=restore;$('showPassword').onclick=()=>{const visible=$('password').type==='password';$('password').type=visible?'text':'password';$('showPassword').textContent=visible?'Ocultar':'Mostrar';$('showPassword').setAttribute('aria-label',visible?'Ocultar senha':'Mostrar senha');};$('year').textContent=new Date().getFullYear();
window.addEventListener('storage',e=>{if(e.key===KEY){showLogin();restore();}});
(async()=>{try{const data=await api('/api/auth/status',{token:null});$('username').replaceChildren(new Option('Selecione sua conta',''),...(data.usuarios||[]).filter(u=>u.perfil!=='apresentacao').map(u=>new Option((u.nome||u.usuario)+' · @'+u.usuario,u.usuario)));if(params.get('trocar')==='1')await signOut();else await restore();}catch(e){$('username').replaceChildren(new Option('Informe seu usuário',''));const input=document.createElement('input');input.id='username';input.name='username';input.autocomplete='username';input.required=true;$('username').replaceWith(input);message('Não foi possível carregar a lista. Digite seu usuário e tente entrar.');}})();
